# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(850, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_load_t = QtWidgets.QPushButton(self.frame)
        self.button_load_t.setObjectName("button_load_t")
        self.horizontalLayout_4.addWidget(self.button_load_t)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.button_save = QtWidgets.QPushButton(self.frame)
        self.button_save.setObjectName("button_save")
        self.verticalLayout_10.addWidget(self.button_save)
        self.button_opensave = QtWidgets.QPushButton(self.frame)
        self.button_opensave.setObjectName("button_opensave")
        self.verticalLayout_10.addWidget(self.button_opensave)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.cb_auto_next = QtWidgets.QCheckBox(self.frame)
        self.cb_auto_next.setChecked(True)
        self.cb_auto_next.setObjectName("cb_auto_next")
        self.horizontalLayout_4.addWidget(self.cb_auto_next)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.button_next = QtWidgets.QPushButton(self.frame)
        self.button_next.setObjectName("button_next")
        self.verticalLayout_8.addWidget(self.button_next)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.button_reset_num = QtWidgets.QPushButton(self.frame)
        self.button_reset_num.setObjectName("button_reset_num")
        self.verticalLayout_9.addWidget(self.button_reset_num)
        self.button_fill = QtWidgets.QPushButton(self.frame)
        self.button_fill.setObjectName("button_fill")
        self.verticalLayout_9.addWidget(self.button_fill)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.edit_target_name_location = QtWidgets.QLineEdit(self.frame)
        self.edit_target_name_location.setMinimumSize(QtCore.QSize(120, 0))
        self.edit_target_name_location.setObjectName("edit_target_name_location")
        self.horizontalLayout_5.addWidget(self.edit_target_name_location)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.edit_target_name_location_non = QtWidgets.QLineEdit(self.frame)
        self.edit_target_name_location_non.setMinimumSize(QtCore.QSize(120, 0))
        self.edit_target_name_location_non.setObjectName("edit_target_name_location_non")
        self.horizontalLayout_5.addWidget(self.edit_target_name_location_non)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.edit_target_num_location = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_target_num_location.sizePolicy().hasHeightForWidth())
        self.edit_target_num_location.setSizePolicy(sizePolicy)
        self.edit_target_num_location.setMaximumSize(QtCore.QSize(40, 16777215))
        self.edit_target_num_location.setObjectName("edit_target_num_location")
        self.horizontalLayout_5.addWidget(self.edit_target_num_location)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.frame)
        self.table_t = QtWidgets.QTableWidget(self.groupBox)
        self.table_t.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_t.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_t.setObjectName("table_t")
        self.table_t.setColumnCount(2)
        self.table_t.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_t.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_t.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.table_t)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.button_load_s = QtWidgets.QPushButton(self.frame_2)
        self.button_load_s.setObjectName("button_load_s")
        self.verticalLayout_5.addWidget(self.button_load_s)
        self.button_output_right = QtWidgets.QPushButton(self.frame_2)
        self.button_output_right.setObjectName("button_output_right")
        self.verticalLayout_5.addWidget(self.button_output_right)
        self.cb_showall = QtWidgets.QCheckBox(self.frame_2)
        self.cb_showall.setChecked(True)
        self.cb_showall.setObjectName("cb_showall")
        self.verticalLayout_5.addWidget(self.cb_showall)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.edit_include = QtWidgets.QLineEdit(self.frame_2)
        self.edit_include.setMinimumSize(QtCore.QSize(120, 0))
        self.edit_include.setObjectName("edit_include")
        self.horizontalLayout_2.addWidget(self.edit_include)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.edit_outclude = QtWidgets.QLineEdit(self.frame_2)
        self.edit_outclude.setMinimumSize(QtCore.QSize(120, 0))
        self.edit_outclude.setObjectName("edit_outclude")
        self.horizontalLayout_3.addWidget(self.edit_outclude)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.table_s = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_s.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_s.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_s.setObjectName("table_s")
        self.table_s.setColumnCount(2)
        self.table_s.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_s.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_s.setHorizontalHeaderItem(1, item)
        self.table_s.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.table_s)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuWef = QtWidgets.QMenu(self.menuBar)
        self.menuWef.setObjectName("menuWef")
        MainWindow.setMenuBar(self.menuBar)
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.menuWef.addAction(self.action_exit)
        self.menuBar.addAction(self.menuWef.menuAction())

        self.retranslateUi(MainWindow)
        self.action_exit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_load_t, self.button_save)
        MainWindow.setTabOrder(self.button_save, self.button_opensave)
        MainWindow.setTabOrder(self.button_opensave, self.cb_auto_next)
        MainWindow.setTabOrder(self.cb_auto_next, self.button_next)
        MainWindow.setTabOrder(self.button_next, self.button_fill)
        MainWindow.setTabOrder(self.button_fill, self.edit_target_name_location)
        MainWindow.setTabOrder(self.edit_target_name_location, self.edit_target_name_location_non)
        MainWindow.setTabOrder(self.edit_target_name_location_non, self.edit_target_num_location)
        MainWindow.setTabOrder(self.edit_target_num_location, self.button_load_s)
        MainWindow.setTabOrder(self.button_load_s, self.button_output_right)
        MainWindow.setTabOrder(self.button_output_right, self.cb_showall)
        MainWindow.setTabOrder(self.cb_showall, self.edit_include)
        MainWindow.setTabOrder(self.edit_include, self.edit_outclude)
        MainWindow.setTabOrder(self.edit_outclude, self.table_t)
        MainWindow.setTabOrder(self.table_t, self.table_s)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "信息点表辅助对应程序（西安图迹）"))
        self.groupBox.setTitle(_translate("MainWindow", "目标点表"))
        self.button_load_t.setText(_translate("MainWindow", "打开"))
        self.button_save.setText(_translate("MainWindow", "输出"))
        self.button_opensave.setText(_translate("MainWindow", "打开输出"))
        self.cb_auto_next.setText(_translate("MainWindow", "自动下一个"))
        self.button_next.setText(_translate("MainWindow", "(&N)下一个"))
        self.button_reset_num.setText(_translate("MainWindow", "(&R)重置点号"))
        self.button_fill.setText(_translate("MainWindow", "(&F)填充点号"))
        self.label_3.setText(_translate("MainWindow", "名称定位"))
        self.label_5.setText(_translate("MainWindow", "不包含"))
        self.label_4.setText(_translate("MainWindow", "点号定位"))
        self.edit_target_num_location.setText(_translate("MainWindow", "-1"))
        item = self.table_t.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "名称"))
        item = self.table_t.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "点号"))
        self.groupBox_2.setTitle(_translate("MainWindow", "源点表"))
        self.button_load_s.setText(_translate("MainWindow", "打开"))
        self.button_output_right.setText(_translate("MainWindow", "导出列表"))
        self.cb_showall.setText(_translate("MainWindow", "仅显示未分配点"))
        self.label.setText(_translate("MainWindow", "  包含"))
        self.label_2.setText(_translate("MainWindow", "不包含"))
        item = self.table_s.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "点号"))
        item = self.table_s.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        self.menuWef.setTitle(_translate("MainWindow", "开始"))
        self.action_exit.setText(_translate("MainWindow", "退出"))

from ui.resource_rc import *
